### ISSUE TITLE
Validateur FHIR - V FSH - Mettre à jour les validateurs en Pprod et Prod + qualif

### ISSUE THREAD

**Issue by jguihot** [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation#126]
## Description du problème

A faire une fois le package IG finalisé

- [x] Mettre à jour le package sur matchbox sur Acceptance
- [x] qualification des validateurs sur Acceptance
- [x] Mettre à jour le package sur matchbox en Pprod
- [x] qualification des validateurs en Pprod
- [x] Mettre à jour le package sur matchbox en Prod
- [x] qualification des validateurs en Prod

## Fichier•s concerné•s
StructureDef
Validateurs sur Gazelle

## Solution proposée

**Comment by TristanKEREVAL** [comment]
Problème de validation avec serveur de terminologie pour l'attribut contentType du profil sdoDocumentReference.

Sans serveur de terminologie : The value provided ('text/plain') could not be validated because the code system urn:ietf:bcp:13 is not known

Avec le FTS fhir (https://tx.fhir.org/) : Pas de message/warning/error mais pas de validation du code

Avec le SMT (https://smt.esante.gouv.fr/fhir/) : erreur The value provided ('text/plain') is not in the value set 'MimeType' (http://hl7.org/fhir/ValueSet/mimetypes|4.0.1), and a code is required from this value set (error message = Error from https://smt.esante.gouv.fr/fhir/: Error:[bfd4564a-e666-4806-900b-a80a9bc76c6f]: A usable code system with URL urn:ietf:bcp:13 could not be resolved. )

Plusieurs problèmes apparaissent sur les serveurs de terminologie : 

- Sur le SMT : 
   - Impossible de faire l'expansion car il trouve pas le ValueSet
   - A une erreur
Sur le FTS de Grahame :
   - Impossible de faire l'expansion : "The code System "urn:ietf:bcp:13" has a grammar, and cannot be enumerated directly"
N'affiche pas d'erreur sur matchbox quel que soit le code entré, pas validé

**Comment by TristanKEREVAL** [comment]
Réponse de Matchbox : https://github.com/ahdis/matchbox/issues/224
Le problème semble donc être côté SMT

**Comment by jguihot** [comment]
@nriss , ce soucis a été remonté coté SMT ou bien faut-il que nous le fassions suivre ?
@SEBELIN , @mbrulliard , pour info

**Comment by jguihot** [comment]
Synthèse des erreurs et warning remontés lors de la qualification et indépendante du projet:

- [ ] "The value provided ('text/plain') is not in the value set 'MimeType' [...]"
Ressource impactée :  esms-bundle-resultat-recherche-decision-evaluation / esms-document-reference / sdo-document-reference
Level : Error
=>issue matchbox : https://github.com/ahdis/matchbox/issues/224
=>tracé dans l'actuelle issue
=> Conclusion : pas de problème de fonctionnement du JDV mais problème d'interprétation coté SMT = action ANS

- [ ]   "None of the codings provided are in the value set 'DocumentReferenceTypeESMSValueSet' [...]"
Ressource impactée : esms-bundle-resultat-recherche-decision-evaluation
Level : Error
=> Analyse log : root@ansapp020:~# curl -I http://loinc.org HTTP/1.1 403 Forbidden
=> accès serveur à la LOINC non ouvert => action Claranet (en cours)

- [ ] "None of the codings provided are in the value set 'Consent Category"
Ressource impactée :  esms-consent
Level : Warning
=> discordance spec FHIR et LOINC
=> ANS (N. RISS) : "Etant donné que l'erreur est insoluble (incohérence entre LOINC et le ValueSet FHIR), je propose d'ignorer l'erreur" (https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/100)
=> Ticket JIRA aux équipes FHIR : https://jira.hl7.org/browse/FHIR-44625

- [ ]  "None of the codings provided are in the value set 'Consent PolicyRule Codes'"
Ressource impactée : esms-consent
Level : Warning 
=>ANS (N. Riss) : élément imposé par la ressource mais code très pays dépendant. Pas d'usage pour la France et non requis dans la future version de FHIR = laisser en l'état et ignorer l'erreur (https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/32)

- [ ] Warning "ValueSet https://mos.esante.gouv.fr/NOS/JDV_JXX"
Ressource impactée : sdo-bundle-resultat-recherche-notification-esms / sdo-task
Level : Warning
=> création des JDV à prévoir dans les NOS => action ANS

@SEBELIN , pour info

**Comment by jguihot** [comment]
@nriss , @SEBELIN , @mbrulliard, pour information, concernant la 2e anomalie identifiée ci-dessus, le flux LOINC a été ouvert par Claranet et est fonctionnel L'anomalie n'est pas pour autant corrigée. Nous soupçonnons donc que, là encore, le sujet serait à traiter coté SMT.
